config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  get 'recipes/new'
  get 'recipes/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    has_many :user_ingredients
    has_many :users, through: :user_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    has_many :recipes
    has_many :ingredients
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :user_ingredients
    has_many :ingredients, through: :user_ingredients
end

app/models/user_ingredient.rb
class UserIngredient < ApplicationRecord
    has_many :users
    has_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :find_ingredients, only: [:show, :edit, :update, :destroy]
    def index
        @ingredients = Ingredient.all
    end

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.create(ingredient_params)
    end

    def edit
    end

    def update
    end

    def show
        @ingredient = Ingredient.find(params[:id])
    end

    def destroy
    end

    private

    def find_ingredients
        @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
        params.require(:ingredient).permit!  #(:name, :user_id)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
  end

  def destroy
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit!  #(:name, :ingredients)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
    end
    
    def show
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit!  #(:name, :ingredients)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>
<%= render "form" %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>>
<% @ingredients.each do |ingredient| %>
<%=link_to ingredient.name, ingredient_path(ingredient)%>
<% end %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render "form" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>>
<% @recipes.each do |recipe| %>
<%=link_to recipe.name, recipe_path(recipe)%>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render "form" %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render "form" %>

app/views/users/index.html.erb
<h1>Users</h1>>
<% @users.each do |user| %>
<%=link_to user.name, user_path(user)%>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render "form" %>